// AUTOGENERATED - DO NOT MODIFY
import NexusOverview from '../src/views/NexusOverview';import PaymentNexusDetail from '../src/views/PaymentNexusDetail';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-04-12 15:43:05.745098211 -0400 EDT m=+6.357220342';

export { 
  NexusOverview,

  PaymentNexusDetail
 };

export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "distribution_type": "public",
  "icon": "./icon.png",
  "id": "com.taxshieldagent.monitor",
  "name": "TaxShieldAgent",
  "permissions": [
    {
      "permission": "payment_intent_read",
      "purpose": "Read PaymentIntent metadata to extract the destination state for each transaction, enabling per-state sales aggregation and Economic Nexus threshold monitoring across all 50 US states."
    },
    {
      "permission": "tax_settings_write",
      "purpose": "Create Stripe Tax Registrations in US states when a merchant approves a compliance fix. Registration only occurs after explicit merchant confirmation — the app never acts autonomously."
    },
    {
      "permission": "charge_write",
      "purpose": "Apply a $1 application fee to the merchant's most recent charge when a state tax registration is successfully completed. This is the app's per-action monetisation fee."
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://api.taxshieldagent.com/stripe-app/stripe-app-callback"
  },
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://api.taxshieldagent.com/stripe-app/",
        "https://api.taxshieldagent.com/nexus/"
      ],
      "purpose": "Connect to TaxShieldAgent backend API for nexus risk data and compliance actions"
    },
    "views": [
      {
        "component": "NexusOverview",
        "viewport": "stripe.dashboard.home.overview"
      },
      {
        "component": "PaymentNexusDetail",
        "viewport": "stripe.dashboard.payment.detail"
      }
    ]
  },
  "version": "0.4.2"
};
